package imp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2011-12-13T00:43:55.938-04:30
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://imp/", name = "ImpServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ImpServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eliminarRelacionPaciente", targetNamespace = "http://imp/", className = "imp.EliminarRelacionPaciente")
    @WebMethod
    @ResponseWrapper(localName = "eliminarRelacionPacienteResponse", targetNamespace = "http://imp/", className = "imp.EliminarRelacionPacienteResponse")
    public java.lang.Object eliminarRelacionPaciente();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "editarPaciente", targetNamespace = "http://imp/", className = "imp.EditarPaciente")
    @WebMethod
    @ResponseWrapper(localName = "editarPacienteResponse", targetNamespace = "http://imp/", className = "imp.EditarPacienteResponse")
    public java.lang.Object editarPaciente(
        @WebParam(name = "paciente", targetNamespace = "")
        java.lang.String paciente
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "agregarPaciente", targetNamespace = "http://imp/", className = "imp.AgregarPaciente")
    @WebMethod
    @ResponseWrapper(localName = "agregarPacienteResponse", targetNamespace = "http://imp/", className = "imp.AgregarPacienteResponse")
    public boolean agregarPaciente(
        @WebParam(name = "paciente", targetNamespace = "")
        imp.PacienteArr paciente,
        @WebParam(name = "idOrganizacion", targetNamespace = "")
        java.lang.String idOrganizacion
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "modificarRelacionPaciente", targetNamespace = "http://imp/", className = "imp.ModificarRelacionPaciente")
    @WebMethod
    @ResponseWrapper(localName = "modificarRelacionPacienteResponse", targetNamespace = "http://imp/", className = "imp.ModificarRelacionPacienteResponse")
    public java.lang.Object modificarRelacionPaciente();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCandidatos", targetNamespace = "http://imp/", className = "imp.BuscarCandidatos")
    @WebMethod
    @ResponseWrapper(localName = "buscarCandidatosResponse", targetNamespace = "http://imp/", className = "imp.BuscarCandidatosResponse")
    public java.lang.Object buscarCandidatos();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "agregarRelacionPaciente", targetNamespace = "http://imp/", className = "imp.AgregarRelacionPaciente")
    @WebMethod
    @ResponseWrapper(localName = "agregarRelacionPacienteResponse", targetNamespace = "http://imp/", className = "imp.AgregarRelacionPacienteResponse")
    public java.lang.Object agregarRelacionPaciente();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "eliminarPaciente", targetNamespace = "http://imp/", className = "imp.EliminarPaciente")
    @WebMethod
    @ResponseWrapper(localName = "eliminarPacienteResponse", targetNamespace = "http://imp/", className = "imp.EliminarPacienteResponse")
    public boolean eliminarPaciente(
        @WebParam(name = "IdPacienteOrg", targetNamespace = "")
        java.lang.String idPacienteOrg,
        @WebParam(name = "idOrganizacion", targetNamespace = "")
        java.lang.String idOrganizacion
    );
}
