package cda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.4
 * 2011-12-13T00:43:52.716-04:30
 * Generated source version: 2.4.4
 * 
 */
@WebService(targetNamespace = "http://cda/", name = "CdaServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CdaServicePortType {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCDAByRango", targetNamespace = "http://cda/", className = "cda.BuscarCDAByRango")
    @WebMethod
    @ResponseWrapper(localName = "buscarCDAByRangoResponse", targetNamespace = "http://cda/", className = "cda.BuscarCDAByRangoResponse")
    public java.util.List<cda.CdaArr> buscarCDAByRango(
        @WebParam(name = "desde", targetNamespace = "")
        java.lang.Object desde,
        @WebParam(name = "hasta", targetNamespace = "")
        java.lang.Object hasta,
        @WebParam(name = "offset", targetNamespace = "")
        java.lang.Object offset
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCDAByPacienteAndOrganizacion", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPacienteAndOrganizacion")
    @WebMethod
    @ResponseWrapper(localName = "buscarCDAByPacienteAndOrganizacionResponse", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPacienteAndOrganizacionResponse")
    public java.util.List<cda.CdaArr> buscarCDAByPacienteAndOrganizacion(
        @WebParam(name = "paciente", targetNamespace = "")
        java.lang.String paciente,
        @WebParam(name = "organizacion", targetNamespace = "")
        java.lang.String organizacion,
        @WebParam(name = "offset", targetNamespace = "")
        java.lang.Object offset
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCDAByPacienteAndRango", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPacienteAndRango")
    @WebMethod
    @ResponseWrapper(localName = "buscarCDAByPacienteAndRangoResponse", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPacienteAndRangoResponse")
    public java.util.List<cda.CdaArr> buscarCDAByPacienteAndRango(
        @WebParam(name = "paciente", targetNamespace = "")
        java.lang.Object paciente,
        @WebParam(name = "desde", targetNamespace = "")
        java.lang.Object desde,
        @WebParam(name = "hasta", targetNamespace = "")
        java.lang.Object hasta,
        @WebParam(name = "offset", targetNamespace = "")
        java.lang.Object offset
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCDAByPaciente", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPaciente")
    @WebMethod
    @ResponseWrapper(localName = "buscarCDAByPacienteResponse", targetNamespace = "http://cda/", className = "cda.BuscarCDAByPacienteResponse")
    public java.util.List<cda.CdaArr> buscarCDAByPaciente(
        @WebParam(name = "paciente", targetNamespace = "")
        java.lang.String paciente,
        @WebParam(name = "offset", targetNamespace = "")
        java.lang.Object offset
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registrarCDA", targetNamespace = "http://cda/", className = "cda.RegistrarCDA")
    @WebMethod
    @ResponseWrapper(localName = "registrarCDAResponse", targetNamespace = "http://cda/", className = "cda.RegistrarCDAResponse")
    public java.lang.Object registrarCDA(
        @WebParam(name = "cda", targetNamespace = "")
        java.lang.String cda
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "buscarCDAById", targetNamespace = "http://cda/", className = "cda.BuscarCDAById")
    @WebMethod
    @ResponseWrapper(localName = "buscarCDAByIdResponse", targetNamespace = "http://cda/", className = "cda.BuscarCDAByIdResponse")
    public cda.CdaArr buscarCDAById(
        @WebParam(name = "id", targetNamespace = "")
        int id
    );
}
